version: '3.1'

services:
  postgres-odoo:
    image: postgres:15
    container_name: postgres-odoo
    environment:
      - POSTGRES_DB=ninja_quiz_db
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    networks:
      - odoo-net
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo17:
    image: odoo:17
    container_name: odoo17
    depends_on:
      - postgres-odoo
    ports:
      - "8070:8069"
    volumes:
      - ./mis_addons:/mnt/extra-addons
    networks:
      - odoo-net
    environment:
      - HOST=postgres-odoo
      - USER=odoo
      - PASSWORD=odoo

networks:
  odoo-net:
    driver: bridge

volumes:
  odoo-db-data:
